# Generated by Django 5.1.6 on 2025-12-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('material', '0003_alter_hardware_unique_together'),
        ('products1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='billing_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.billingunit'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='measurement_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.measurementunit'),
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='purchase_price_positive',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='selling_price_positive',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products1_p_is_acti_917674_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products1_p_created_efc835_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products1_p_is_acti_03e25d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productseries',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variantattributevalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantimage',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='productseries',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.DeleteModel(
            name='BillingUnit',
        ),
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
    ]
