# Generated by Django 5.1.6 on 2025-12-14 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.AlterModelOptions(
            name='attributedefinition',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='billingunit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='measurementunit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products1.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active'], name='products1_p_is_acti_03e25d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='purchase_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='selling_price_positive'),
        ),
        migrations.AddField(
            model_name='productseries',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='products1.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products1.productseries'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products1_p_is_acti_917674_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products1_p_created_efc835_idx'),
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.AlterUniqueTogether(
            name='productseries',
            unique_together={('product_type', 'name')},
        ),
    ]
