# Generated by Django 5.1.6 on 2026-02-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_globalvariable_options_alter_tenant_options_and_more'),
        ('products1', '0004_producttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products1.productbundle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products1.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'bundle', 'product')},
            },
        ),
    ]
