# Generated by Django 5.1.6 on 2025-06-13 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_remove_hardware_sl_price_alter_hardware_unit_and_more'),
        ('pmodular', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='material',
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='compatible_wooden_materials',
            field=models.ManyToManyField(blank=True, help_text="Select specific WoodEn sheet materials compatible with this module's design.", limit_choices_to={'is_sheet': True}, related_name='eligible_modules', to='material.wooden'),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='height_mm_max',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum configurable height of the module in mm.', max_digits=10),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='height_mm_min',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum configurable height of the module in mm.', max_digits=10),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='length_mm_max',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum configurable length of the module in mm.', max_digits=10),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='length_mm_min',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum configurable length of the module in mm.', max_digits=10),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='width_mm_max',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum configurable width of the module in mm.', max_digits=10),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='width_mm_min',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum configurable width of the module in mm.', max_digits=10),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='edgeband_material',
            field=models.ForeignKey(blank=True, help_text='Select an EdgeBand material if this component requires edge banding.', null=True, on_delete=django.db.models.deletion.PROTECT, to='material.edgeband'),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='hardware_material',
            field=models.ForeignKey(blank=True, help_text='Select a Hardware item if this component includes specific hardware.', null=True, on_delete=django.db.models.deletion.PROTECT, to='material.hardware'),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='wooden_material',
            field=models.ForeignKey(blank=True, help_text='Select a WoodEn material if this component is made of wood.', null=True, on_delete=django.db.models.deletion.PROTECT, to='material.wooden'),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='height_mm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default height (for calculation) of the module in mm (should be within min/max range).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='length_mm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default length (for calculation) of the module in mm (should be within min/max range).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='width_mm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default width (for calculation) of the module in mm (should be within min/max range).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='edge_band_cost_formula',
            field=models.CharField(default='0.0', help_text="Formula for total edge banding cost for one component. Use 'material_by_name()' to fetch edge bands.", max_length=500),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='hardware_cost_formula',
            field=models.CharField(default='0.0', help_text="Formula for total hardware cost for one component. Use 'material_by_name()' to fetch other hardware.", max_length=500),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='purchase_cost_per_unit_formula',
            field=models.CharField(default='0.0', help_text="Formula for component's material purchase cost per unit. Use 'material_cost_per_unit'.", max_length=500),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='sell_price_per_unit_formula',
            field=models.CharField(default='0.0', help_text="Formula for component's material selling price per unit. Use 'material_sell_per_unit'.", max_length=500),
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
