# Generated by Django 5.1.6 on 2025-06-14 00:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_remove_hardware_sl_price_alter_hardware_unit_and_more'),
        ('pmodular', '0002_remove_furnituremodulecomponent_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furnituremodulecomponent',
            options={'ordering': ['module', 'order', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='furnituremodulecomponent',
            unique_together={('module', 'name')},
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='edge_band_cost_formula',
            field=models.TextField(default='0.0', help_text='Formula for edge band cost per unit of this component.'),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='edgeband_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_edgeband', to='material.edgeband'),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='hardware_cost_formula',
            field=models.TextField(default='0.0', help_text='Formula for additional hardware cost per unit of this component.'),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='hardware_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_hardware', to='material.hardware'),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='labor_cost_formula',
            field=models.TextField(default='0.0', help_text='Formula for labor cost per unit of this component.'),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='length_formula',
            field=models.TextField(help_text="Formula for component length in mm (e.g., 'L - (2 * INTERNAL_WALL_THICKNESS)')."),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of this component within the module for display/calculation.'),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='part_thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Override thickness in mm if different from material's default.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='quantity_formula',
            field=models.TextField(help_text="Formula for number of units of this component (e.g., '1' or 'H / SHELF_SPACING')."),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='wastage_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional wastage factor for this specific component (e.g., 0.05 for 5% extra).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='width_formula',
            field=models.TextField(help_text="Formula for component width in mm (e.g., 'W / 2 - INTERNAL_GAP')."),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='wooden_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_wood', to='material.wooden'),
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='purchase_cost_per_unit_formula',
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='sell_price_per_unit_formula',
        ),
    ]
