# Generated by Django 5.1.6 on 2025-06-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmodular', '0003_alter_furnituremodulecomponent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='part_thickness_mm',
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='length_formula',
            field=models.TextField(help_text="Formula for component length in mm (e.g., 'L - (2 * MATERIAL_THICKNESS_MM)')."),
        ),
    ]
