# Generated by Django 5.1.6 on 2025-06-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmodular', '0004_remove_furnituremodulecomponent_part_thickness_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituremodule',
            name='component_cost_defaults',
            field=models.JSONField(blank=True, default=dict, help_text="JSON defining default formulas for various component cost types. E.g., {'wooden_panel': {'labor': '...', 'hardware': '...', 'edge_band': '...'}, 'drawer': {...}}", null=True),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='cost_formula_key',
            field=models.CharField(blank=True, help_text="A key (e.g., 'wooden_panel', 'drawer_front') to fetch default labor, hardware, edge band formulas from the module. If blank, no module defaults are applied.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='edge_band_cost_formula',
            field=models.TextField(blank=True, help_text="Override formula for edge band cost. If blank, module's default for 'cost_formula_key' is used.", null=True),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='hardware_cost_formula',
            field=models.TextField(blank=True, help_text="Override formula for hardware cost. If blank, module's default for 'cost_formula_key' is used.", null=True),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='labor_cost_formula',
            field=models.TextField(blank=True, help_text="Override formula for labor cost. If blank, module's default for 'cost_formula_key' is used.", null=True),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='length_formula',
            field=models.TextField(help_text='Formula for component length in mm (e.g., \'H - components_by_name["Top Panel"]["MATERIAL_THICKNESS_MM"]\').'),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='width_formula',
            field=models.TextField(help_text='Formula for component width in mm (e.g., \'W - components_by_name["Left Side Panel"]["MATERIAL_THICKNESS_MM"]\').'),
        ),
    ]
