# Generated by Django 5.1.6 on 2025-06-14 22:30

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_remove_hardware_sl_price_alter_hardware_unit_and_more'),
        ('pmodular', '0005_furnituremodule_component_cost_defaults_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appglobalsetting',
            options={'ordering': ['name'], 'verbose_name': 'App Global Setting', 'verbose_name_plural': 'App Global Settings'},
        ),
        migrations.AlterModelOptions(
            name='furnituremodule',
            options={'verbose_name': 'Furniture Module', 'verbose_name_plural': 'Furniture Modules'},
        ),
        migrations.AlterModelOptions(
            name='furnituremodulecomponent',
            options={'verbose_name': 'Module Component', 'verbose_name_plural': 'Module Components'},
        ),
        migrations.RemoveField(
            model_name='appglobalsetting',
            name='boolean_value',
        ),
        migrations.RemoveField(
            model_name='appglobalsetting',
            name='decimal_value',
        ),
        migrations.RemoveField(
            model_name='appglobalsetting',
            name='string_value',
        ),
        migrations.RemoveField(
            model_name='furnituremodule',
            name='component_cost_defaults',
        ),
        migrations.RemoveField(
            model_name='furnituremodule',
            name='height_mm',
        ),
        migrations.RemoveField(
            model_name='furnituremodule',
            name='length_mm',
        ),
        migrations.RemoveField(
            model_name='furnituremodule',
            name='width_mm',
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='cost_formula_key',
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='edge_band_cost_formula',
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='edgeband_material',
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='hardware_cost_formula',
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='hardware_material',
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='wastage_factor',
        ),
        migrations.RemoveField(
            model_name='furnituremodulecomponent',
            name='wooden_material',
        ),
        migrations.AddField(
            model_name='appglobalsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appglobalsetting',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of what this setting controls.', null=True),
        ),
        migrations.AddField(
            model_name='appglobalsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appglobalsetting',
            name='value',
            field=models.TextField(default=0, help_text="The value of the setting. Type specified by 'value_type'."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appglobalsetting',
            name='value_type',
            field=models.CharField(choices=[('decimal', 'Decimal Number'), ('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean')], default='decimal', help_text='Data type of the value to ensure correct parsing.', max_length=10),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='base_hardware_item',
            field=models.ForeignKey(blank=True, help_text='The default hardware item for module-level calculations.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.hardware'),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='base_hardware_quantity_formula',
            field=models.CharField(blank=True, help_text="Formula for default quantity of module-level hardware. E.g., '2 if H > 500 else 1'. Variables: L, W, H.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='cost_formulas',
            field=models.JSONField(blank=True, default=dict, help_text="JSON defining default formulas for various cost types for components belonging to this module. Variables: L, W, H (module dimensions), other global settings. E.g., {'labor_cost_base': 'L * W * H * LABOR_RATE'}", null=True),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='height_mm_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('720.00'), help_text='Default height for calculations, within min/max.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='length_mm_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('600.00'), help_text='Default length for calculations, within min/max.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='furnituremodule',
            name='width_mm_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('600.00'), help_text='Default width for calculations, within min/max.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='default_edge_band_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_eb_B', to='material.edgeband'),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='default_edge_band_L',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_eb_L', to='material.edgeband'),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='default_edge_band_R',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_eb_R', to='material.edgeband'),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='default_edge_band_T',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_eb_T', to='material.edgeband'),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='default_edge_band_sides',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('T', 'Top'), ('B', 'Bottom')], max_length=1), blank=True, default=list, help_text='Default sides to edge band for this component (L, R, T, B).', size=None),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='default_hardware_material',
            field=models.ForeignKey(blank=True, help_text='Default hardware item for this component. Quantity via quantity_formula.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.hardware'),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='default_wooden_material',
            field=models.ForeignKey(blank=True, help_text='Default wooden material for this component.', limit_choices_to={'is_sheet': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.wooden'),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furnituremodulecomponent',
            name='grooving_cost_formula',
            field=models.CharField(blank=True, help_text="Formula for grooving cost contributed by this component. E.g., '0.5 * TOTAL_EDGE_LENGTH_CALC * GROOVING_RATE_PER_MM'", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appglobalsetting',
            name='name',
            field=models.CharField(help_text="Unique name for the setting (e.g., 'BLADE_SIZE_MM', 'STANDARD_LABOR_RATE_PER_SQFT').", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='constraints',
            field=models.JSONField(blank=True, default=dict, help_text="Module-specific constraints (e.g., {'INTERNAL_GAP': 5}). These override global settings defined in AppGlobalSetting.", null=True),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='height_mm_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('2400.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='height_mm_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='length_mm_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('3000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='length_mm_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='width_mm_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('1200.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='furnituremodule',
            name='width_mm_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='labor_cost_formula',
            field=models.CharField(blank=True, help_text="Formula for labor cost contributed by this component. E.g., '0.0001 * L_CALC * W_CALC * Q_CALC * STANDARD_LABOR_RATE_PER_SQFT'", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='length_formula',
            field=models.CharField(help_text="Formula for component length in mm. E.g., 'L - 2 * MATERIAL_THICKNESS_MM'", max_length=500),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pmodular.furnituremodule'),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='name',
            field=models.CharField(help_text="Name of the component (e.g., 'Top Panel', 'Side Left').", max_length=255),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='quantity_formula',
            field=models.CharField(default='1', help_text="Formula for number of units of this component. E.g., '2' or '2 if L > 1000 else 1'", max_length=500),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='width_formula',
            field=models.CharField(help_text="Formula for component width in mm. E.g., 'W - 2 * BLADE_SIZE_MM'", max_length=500),
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.DecimalField(decimal_places=2, help_text="Configured length of the module in mm (must be within module's min/max range).", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('width_mm', models.DecimalField(decimal_places=2, help_text="Configured width of the module in mm (must be within module's min/max range).", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('height_mm', models.DecimalField(decimal_places=2, help_text="Configured height of the module in mm (must be within module's min/max range).", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('material_selling_price_overrides', models.JSONField(blank=True, default=dict, help_text='JSON of material selling price overrides (material_name: new_s_price). Employee controlled. Applied per unit/area based on material type.', null=True)),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_selling_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cost_breakdown_json', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, help_text='The user or employee who configured this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('furniture_module', models.ForeignKey(help_text='The base module definition this configuration is based on.', on_delete=django.db.models.deletion.PROTECT, to='pmodular.furnituremodule')),
                ('selected_wooden_material', models.ForeignKey(blank=True, help_text="The specific wooden material chosen for this configuration (overrides module's compatible default).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.wooden')),
            ],
            options={
                'verbose_name': 'Product Configuration',
                'verbose_name_plural': 'Product Configurations',
            },
        ),
        migrations.CreateModel(
            name='ConfiguredPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm_calc', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('width_mm_calc', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity_calc', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_edge_band_sides', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('T', 'Top'), ('B', 'Bottom')], max_length=1), blank=True, default=list, help_text='Actual sides edge-banded for this configured part (L, R, T, B).', size=None)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('selling_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('individual_breakdown_json', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of costs for this specific part (e.g., material, labor, edge band).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_edge_band_B', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configured_eb_B', to='material.edgeband')),
                ('actual_edge_band_L', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configured_eb_L', to='material.edgeband')),
                ('actual_edge_band_R', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configured_eb_R', to='material.edgeband')),
                ('actual_edge_band_T', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configured_eb_T', to='material.edgeband')),
                ('actual_hardware_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.hardware')),
                ('actual_wooden_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.wooden')),
                ('component_template', models.ForeignKey(help_text='The template component this part is derived from.', on_delete=django.db.models.deletion.PROTECT, to='pmodular.furnituremodulecomponent')),
                ('product_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_parts', to='pmodular.productconfiguration')),
            ],
            options={
                'verbose_name': 'Configured Part',
                'verbose_name_plural': 'Configured Parts',
                'unique_together': {('product_configuration', 'component_template')},
            },
        ),
    ]
