# Generated by Django 5.1.6 on 2025-06-14 22:50

import django.contrib.postgres.fields
import pmodular.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmodular', '0006_alter_appglobalsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuredpart',
            name='actual_edge_band_sides',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('T', 'Top'), ('B', 'Bottom')], max_length=1), blank=True, default=pmodular.models.get_default_array_list, size=None, verbose_name='Actual Edge Banded Sides'),
        ),
        migrations.AlterField(
            model_name='furnituremodulecomponent',
            name='default_edge_band_sides',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('T', 'Top'), ('B', 'Bottom')], max_length=1), blank=True, default=pmodular.models.get_default_array_list, size=None, verbose_name='Default Edge Banded Sides'),
        ),
    ]
