# Generated by Django 5.1.6 on 2026-01-13 01:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_globalvariable_options_alter_tenant_options_and_more'),
        ('material', '0002_alter_billingunit_tenant_alter_brand_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractiveCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('typeofcost', models.CharField(max_length=100)),
                ('cost_equation', models.CharField(help_text="Equation to calculate the cost (e.g., 'product_length * 0.5')", max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modular1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('product_validation_expression', models.TextField(blank=True, help_text='Use product_length, product_width, product_height for validation.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Modular Product',
                'verbose_name_plural': 'Modular Products',
            },
        ),
        migrations.CreateModel(
            name='HardwareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. '2 per door'", max_length=100)),
                ('equation', models.CharField(help_text="e.g. 'num_doors * 2'", max_length=255)),
                ('is_custom', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('modular_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_rules', to='partisoproduct.modular1')),
            ],
            options={
                'verbose_name': 'Hardware Rule',
                'verbose_name_plural': 'Hardware Rules',
                'unique_together': {('modular_product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MvpQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MvpQuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('modular_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partisoproduct.modular1')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='partisoproduct.mvpquoterequest')),
            ],
        ),
        migrations.CreateModel(
            name='Part1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('part_length_equation', models.CharField(max_length=255)),
                ('part_width_equation', models.CharField(max_length=255)),
                ('part_qty_equation', models.CharField(max_length=255)),
                ('part_shape', models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('curvilinear', 'Curvilinear'), ('l_shape', 'L Shape'), ('triangle', 'Triangle')], default='rectangle', max_length=50)),
                ('grain_direction', models.CharField(choices=[('none', 'None'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='none', max_length=20)),
                ('part_dimensions', models.JSONField(default=dict)),
                ('shape_wastage_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('hardware_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hardware_total_sell', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compatible_categories', models.ManyToManyField(blank=True, related_name='parts_by_category', to='material.category')),
                ('compatible_models', models.ManyToManyField(blank=True, related_name='parts_by_model', to='material.categorymodel')),
                ('compatible_types', models.ManyToManyField(blank=True, related_name='parts_by_type', to='material.categorytypes')),
                ('compatible_woods', models.ManyToManyField(blank=True, related_name='parts_by_wood', to='material.woodmaterial')),
                ('modular_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='partisoproduct.modular1')),
                ('part_edgematerial_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_bottom_edges', to='material.edgeband')),
                ('part_edgematerial_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_left_edges', to='material.edgeband')),
                ('part_edgematerial_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_right_edges', to='material.edgeband')),
                ('part_edgematerial_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_top_edges', to='material.edgeband')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MvpQuotePartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('evaluated_dimensions', models.JSONField(default=dict)),
                ('evaluated_qty', models.PositiveIntegerField()),
                ('evaluated_area', models.DecimalField(decimal_places=4, max_digits=10)),
                ('wastage_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edge_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hardware_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('selected_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.woodmaterial')),
                ('quote_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_details', to='partisoproduct.mvpquoteproduct')),
                ('part_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partisoproduct.part1')),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('modular_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='partisoproduct.modular1')),
            ],
            options={
                'verbose_name': 'Product Parameter',
                'verbose_name_plural': 'Product Parameters',
                'unique_together': {('modular_product', 'abbreviation')},
            },
        ),
        migrations.CreateModel(
            name='MvpPartHardwareRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_equation', models.CharField(blank=True, max_length=255, null=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.hardware')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partisoproduct.hardwarerule')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_requirements', to='partisoproduct.part1')),
            ],
            options={
                'verbose_name': 'Part Hardware Requirement',
                'unique_together': {('part', 'hardware', 'rule')},
            },
        ),
    ]
