# Generated by Django 5.1 on 2025-06-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('billing_street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_state', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS')], default='email', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
                ('signup_source', models.CharField(blank=True, choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('referral', 'Referral'), ('social_media', 'Social Media')], max_length=50, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('address_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
