# Generated by Django 5.1.6 on 2025-12-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-interaction_date']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='client',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticket',
            name='tenant',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customer.client'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('tenant', 'email')},
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['tenant', 'interaction_type'], name='customer_in_tenant__a08f88_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'status'], name='customer_le_tenant__5b1b41_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'stage'], name='customer_op_tenant__a134c6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant', 'status', 'priority'], name='customer_su_tenant__7e584b_idx'),
        ),
    ]
