# Generated by Django 5.1.6 on 2025-08-24 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0002_alter_edgeband_unique_together_edgebandname_depth_and_more'),
        ('modular_calc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('part_qty', models.PositiveIntegerField(default=1)),
                ('thickness_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('override_by_employee', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, max_length=255)),
                ('shape_wastage_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('area_mm2', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('area_sqft', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cutting_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('making_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('edgeband_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.wooden')),
                ('part_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modular_calc.parttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='OverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='quoting.quotepart')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('depth_mm', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('validated', models.BooleanField(default=False)),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modular_calc.modularproduct')),
            ],
        ),
        migrations.AddField(
            model_name='quotepart',
            name='quote_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='quoting.quoteproduct'),
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quoting.quoterequest'),
        ),
        migrations.CreateModel(
            name='QuotePartHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.hardware')),
                ('quote_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='quoting.quotepart')),
            ],
            options={
                'unique_together': {('quote_part', 'hardware')},
            },
        ),
        migrations.AddIndex(
            model_name='quoteproduct',
            index=models.Index(fields=['quote', 'product_template'], name='quoting_quo_quote_i_8c2ca1_idx'),
        ),
    ]
