# Generated by Django 5.1.6 on 2026-01-11 00:29

import django.db.models.deletion
import rest_framework.viewsets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customer', '0001_initial'),
        ('material', '0001_initial'),
        ('modular_calc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverrideLogViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rest_framework.viewsets.ReadOnlyModelViewSet),
        ),
        migrations.CreateModel(
            name='QuoteCommunicationViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rest_framework.viewsets.ModelViewSet),
        ),
        migrations.CreateModel(
            name='QuotePartHardwareViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rest_framework.viewsets.ModelViewSet),
        ),
        migrations.CreateModel(
            name='QuotePartViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rest_framework.viewsets.ModelViewSet),
        ),
        migrations.CreateModel(
            name='QuoteProductViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rest_framework.viewsets.ModelViewSet),
        ),
        migrations.CreateModel(
            name='QuoteRequestViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rest_framework.viewsets.ModelViewSet),
        ),
        migrations.CreateModel(
            name='QuoteRevisionViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rest_framework.viewsets.ReadOnlyModelViewSet),
        ),
        migrations.CreateModel(
            name='QuotePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_name', models.CharField(max_length=255)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thickness_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('part_qty', models.PositiveIntegerField(default=1)),
                ('grain_direction', models.CharField(default='none', max_length=20)),
                ('total_part_cp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_part_sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('two_d_svg_path', models.TextField(blank=True, null=True)),
                ('edgeband_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='material.woodmaterial')),
                ('part_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modular_calc.parttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
                ('quote_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='quoting.quotepart')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('config_parameters', models.JSONField(blank=True, default=dict)),
                ('total_cp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('validated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('editable', 'Editable'), ('frozen', 'Frozen')], default='editable', max_length=20)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('override_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.woodmaterial')),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modular_calc.modularproduct')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='quotepart',
            name='quote_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='quoting.quoteproduct'),
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_display_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('locked', 'Locked'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_cp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quote_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customer.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_quotes', to=settings.AUTH_USER_MODEL)),
                ('marketplace_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customer.marketplacecustomer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quoting.quoterequest'),
        ),
        migrations.CreateModel(
            name='QuoteCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('pdf', 'PDF')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='quoting.quoterequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_no', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='quoting.quoterequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-revision_no'],
            },
        ),
        migrations.CreateModel(
            name='QuotePartHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.hardware')),
                ('quote_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='quoting.quotepart')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'quote_part', 'hardware')},
            },
        ),
        migrations.AddIndex(
            model_name='quoteproduct',
            index=models.Index(fields=['tenant', 'quote', 'product_template'], name='quoting_quo_tenant__457a48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quoterevision',
            unique_together={('tenant', 'quote', 'revision_no')},
        ),
    ]
