# Generated by Django 5.1.6 on 2026-01-13 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_globalvariable_options_alter_tenant_options_and_more'),
        ('material', '0002_alter_billingunit_tenant_alter_brand_tenant_and_more'),
        ('modular_calc', '0002_alter_modularproduct_tenant_and_more'),
        ('quoting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('total_cp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='quoteproduct',
            name='quoting_quo_tenant__457a48_idx',
        ),
        migrations.RemoveField(
            model_name='quoteproduct',
            name='quote',
        ),
        migrations.AlterField(
            model_name='overridelog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='quotecommunication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='quoteparthardware',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='quoteproduct',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='quoterevision',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='quotesolution',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='quoting.quoterequest'),
        ),
        migrations.AddField(
            model_name='quotesolution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quoting.quotesolution'),
        ),
        migrations.AddIndex(
            model_name='quoteproduct',
            index=models.Index(fields=['tenant', 'solution', 'product_template'], name='quoting_quo_tenant__d79413_idx'),
        ),
    ]
