# Generated by Django 5.1.6 on 2025-12-23 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('material', '0003_alter_hardware_unique_together'),
        ('modular_calc', '0002_alter_modularproductcategory_options_and_more'),
        ('quoting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quoteproduct',
            name='quoting_quo_quote_i_8c2ca1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='quoteparthardware',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='overridelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overridelog',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overridelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotepart',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotepart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quoteparthardware',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteparthardware',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteparthardware',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='quoteparthardware',
            unique_together={('tenant', 'quote_part', 'hardware')},
        ),
        migrations.AddIndex(
            model_name='quoteproduct',
            index=models.Index(fields=['tenant', 'quote', 'product_template'], name='quoting_quo_tenant__457a48_idx'),
        ),
    ]
