# Generated by Django 5.1.6 on 2026-02-01 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_globalvariable_options_alter_tenant_options_and_more'),
        ('products1', '0003_alter_productvariant_options_and_more'),
        ('quoting', '0002_quotesolution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total_cp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total_sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products1.productbundle')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quoting.quoterequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OverrideLogViewSet',
        ),
        migrations.DeleteModel(
            name='QuoteCommunicationViewSet',
        ),
        migrations.DeleteModel(
            name='QuotePartHardwareViewSet',
        ),
        migrations.DeleteModel(
            name='QuotePartViewSet',
        ),
        migrations.DeleteModel(
            name='QuoteProductViewSet',
        ),
        migrations.DeleteModel(
            name='QuoteRequestViewSet',
        ),
        migrations.DeleteModel(
            name='QuoteRevisionViewSet',
        ),
    ]
