# Generated by Django 5.1.6 on 2026-01-01 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_hardware_unique_together'),
        ('modular_calc', '0005_alter_productparameter_abbreviation_and_more'),
        ('quoting', '0002_remove_quoteproduct_quoting_quo_quote_i_8c2ca1_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overridelog',
            options={'ordering': ['-changed_at']},
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='area_mm2',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='area_sqft',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='cutting_charges',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='making_charges',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='override_by_employee',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='override_reason',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='quotepart',
            name='cnc_details',
            field=models.JSONField(blank=True, default=dict, help_text='Drilling/Grooving coordinates'),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='edgeband_cost_cp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='grain_direction',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='is_manually_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='labour_cost_cp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='material_cost_cp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='override_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='three_d_asset_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='total_part_cp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost to factory', max_digits=12),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='total_part_sp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total price to customer', max_digits=12),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='two_d_svg_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteparthardware',
            name='total_cp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quoteparthardware',
            name='total_sp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quoteparthardware',
            name='unit_cp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost Price per unit at time of quote', max_digits=12),
        ),
        migrations.AddField(
            model_name='quoteparthardware',
            name='unit_sp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling Price per unit at time of quote', max_digits=12),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='config_parameters',
            field=models.JSONField(blank=True, default=dict, help_text="Stores overrides like {'@ST': 25, '@BT': 12}"),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='override_material',
            field=models.ForeignKey(blank=True, help_text='If set, overrides the default material for all parts in this cabinet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.woodmaterial'),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='total_cp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='total_sp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft/Preview'), ('sent', 'Sent to Customer'), ('approved', 'Approved for Production'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='total_cp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Factory Cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='total_sp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Selling Price (Pre-Tax)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='length_mm',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.woodmaterial'),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='part_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modular_calc.parttemplate'),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='width_mm',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quoteproduct',
            name='product_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modular_calc.modularproduct'),
        ),
    ]
