# Generated by Django 5.1.6 on 2026-02-03 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0003_quotelineitem_delete_overridelogviewset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteproduct',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quoting.quoteproduct'),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='source_type',
            field=models.CharField(blank=True, help_text='e.g., bundle, bundle_part, modular_part, template', max_length=50, null=True),
        ),
    ]
