# Generated by Django 5.1.6 on 2026-02-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products1', '0005_bundleitem'),
        ('quoting', '0004_quoteproduct_parent_quoteproduct_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products1.productvariant'),
        ),
    ]
