# Generated by Django 5.1.6 on 2026-02-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0005_quotelineitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='lead_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='revision_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
