# Generated by Django 5.1.6 on 2026-02-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_calc', '0006_alter_partedgebandwhitelist_unique_together'),
        ('products1', '0005_bundleitem'),
        ('quoting', '0006_quoterequest_is_locked_quoterequest_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteproduct',
            name='modular_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modular_calc.modularproduct'),
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products1.productvariant'),
        ),
        migrations.AlterField(
            model_name='quoteproduct',
            name='product_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products1.product'),
        ),
    ]
