# Generated by Django 5.1.6 on 2025-12-20 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModularProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModularProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modular_calc.modularproductcategory')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ModularProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modular_calc.modularproducttype')),
            ],
            options={
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ModularProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product_validation_expression', models.TextField(blank=True, help_text="e.g., '600 <= product_width <= 2400 and 300 <= product_depth <= 700'")),
                ('three_d_asset', models.FileField(blank=True, null=True, upload_to='3d/')),
                ('two_d_template_svg', models.TextField(blank=True, help_text='SVG template with {{placeholders}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modular_calc.modularproductcategory')),
                ('productmodel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modular_calc.modularproductmodel')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modular_calc.modularproducttype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('productmodel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('part_length_equation', models.CharField(max_length=255)),
                ('part_width_equation', models.CharField(max_length=255)),
                ('part_qty_equation', models.CharField(default='1', max_length=255)),
                ('part_thickness_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shape_wastage_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('three_d_asset', models.FileField(blank=True, null=True, upload_to='3d/parts/')),
                ('two_d_template_svg', models.TextField(blank=True)),
                ('edgeband_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_templates', to='modular_calc.modularproduct')),
            ],
            options={
                'ordering': ['product__name', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PartMaterialWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.woodmaterial')),
                ('part_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_whitelist', to='modular_calc.parttemplate')),
            ],
            options={
                'unique_together': {('part_template', 'material')},
            },
        ),
        migrations.CreateModel(
            name='PartHardwareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_equation', models.CharField(default='1', max_length=255)),
                ('applicability_condition', models.TextField(blank=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.hardware')),
                ('part_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_rules', to='modular_calc.parttemplate')),
            ],
            options={
                'unique_together': {('part_template', 'hardware')},
            },
        ),
        migrations.CreateModel(
            name='PartEdgeBandWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], max_length=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('edgeband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.edgeband')),
                ('part_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edgeband_whitelist', to='modular_calc.parttemplate')),
            ],
            options={
                'unique_together': {('part_template', 'side', 'edgeband')},
            },
        ),
        migrations.CreateModel(
            name='ProductHardwareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.hardware')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_rules', to='modular_calc.modularproduct')),
            ],
            options={
                'unique_together': {('product', 'hardware')},
            },
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The variable name used in equations (e.g., 'product_length', 'unit_gap').", max_length=50)),
                ('abbreviation', models.CharField(blank=True, help_text="A short abbreviation for display (e.g., 'L', 'W', 'H').", max_length=10)),
                ('default_value', models.DecimalField(blank=True, decimal_places=2, help_text='A default value for the parameter.', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Explains the purpose and constraints of this parameter.')),
                ('product', models.ForeignKey(help_text='The product this parameter belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='modular_calc.modularproduct')),
            ],
            options={
                'ordering': ['product', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
