# Generated by Django 5.1.6 on 2025-08-24 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0002_alter_edgeband_unique_together_edgebandname_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModularProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('product_validation_expression', models.TextField(blank=True, help_text="e.g., '600 <= product_width <= 2400 and 300 <= product_depth <= 700'")),
                ('three_d_asset', models.FileField(blank=True, null=True, upload_to='3d/')),
                ('two_d_template_svg', models.TextField(blank=True, help_text='SVG template with {{placeholders}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('part_length_equation', models.CharField(max_length=255)),
                ('part_width_equation', models.CharField(max_length=255)),
                ('part_qty_equation', models.CharField(default='1', max_length=255)),
                ('part_thickness_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shape_wastage_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('three_d_asset', models.FileField(blank=True, null=True, upload_to='3d/parts/')),
                ('two_d_template_svg', models.TextField(blank=True)),
                ('edgeband_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('edgeband_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='material.edgeband')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_templates', to='modular_calc.modularproduct')),
            ],
            options={
                'ordering': ['product__name', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PartMaterialWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.wooden')),
                ('part_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_whitelist', to='modular_calc.parttemplate')),
            ],
            options={
                'unique_together': {('part_template', 'material')},
            },
        ),
        migrations.CreateModel(
            name='PartHardwareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_equation', models.CharField(default='1', max_length=255)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.hardware')),
                ('part_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_rules', to='modular_calc.parttemplate')),
            ],
            options={
                'unique_together': {('part_template', 'hardware')},
            },
        ),
        migrations.CreateModel(
            name='PartEdgeBandWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('edgeband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.edgeband')),
                ('part_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edgeband_whitelist', to='modular_calc.parttemplate')),
            ],
            options={
                'unique_together': {('part_template', 'edgeband')},
            },
        ),
    ]
