# Generated by Django 5.1.6 on 2026-01-13 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_globalvariable_options_alter_tenant_options_and_more'),
        ('modular_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularproduct',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='modularproductcategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='modularproductmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='modularproducttype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='partedgebandwhitelist',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='parthardwarerule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='partmaterialwhitelist',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='parttemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='producthardwarerule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
    ]
