# Generated by Django 5.1.6 on 2025-12-23 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('material', '0003_alter_hardware_unique_together'),
        ('modular_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modularproductcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='modularproductmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='modularproducttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='modularproduct',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='modularproductmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='modularproducttype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='partedgebandwhitelist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parthardwarerule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='partmaterialwhitelist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parttemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='producthardwarerule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productparameter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modularproduct',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modularproductcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modularproductcategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='modularproductcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modularproductmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modularproductmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='modularproductmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modularproducttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modularproducttype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='modularproducttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partedgebandwhitelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partedgebandwhitelist',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partedgebandwhitelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parthardwarerule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parthardwarerule',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parthardwarerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partmaterialwhitelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partmaterialwhitelist',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partmaterialwhitelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producthardwarerule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producthardwarerule',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producthardwarerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productparameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productparameter',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productparameter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='modularproduct',
            unique_together={('tenant', 'productmodel', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='modularproductcategory',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='modularproductmodel',
            unique_together={('tenant', 'type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='modularproducttype',
            unique_together={('tenant', 'category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='partedgebandwhitelist',
            unique_together={('part_template', 'side', 'edgeband', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='parthardwarerule',
            unique_together={('part_template', 'hardware', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='partmaterialwhitelist',
            unique_together={('part_template', 'material', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='parttemplate',
            unique_together={('product', 'name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='producthardwarerule',
            unique_together={('product', 'hardware', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='productparameter',
            unique_together={('tenant', 'product', 'name')},
        ),
    ]
