# Generated by Django 5.1.6 on 2025-09-27 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_edgeband_unique_together_edgebandname_depth_and_more'),
        ('modular_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHardwareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.hardware')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_rules', to='modular_calc.modularproduct')),
            ],
            options={
                'unique_together': {('product', 'hardware')},
            },
        ),
        migrations.DeleteModel(
            name='PartHardwareRule',
        ),
    ]
