# Generated by Django 5.1.6 on 2026-01-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_calc', '0002_alter_modularproduct_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularproductcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
