# Generated by Django 5.1.6 on 2025-12-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modular_calc', '0002_alter_modularproductcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttemplate',
            name='part_thickness_mm',
        ),
    ]
