# Generated by Django 5.1.6 on 2025-10-18 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_edgeband_unique_together_edgebandname_depth_and_more'),
        ('modular_calc', '0002_producthardwarerule_delete_parthardwarerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartHardwareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_equation', models.CharField(default='1', max_length=255)),
                ('applicability_condition', models.TextField(blank=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.hardware')),
                ('part_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_rules', to='modular_calc.parttemplate')),
            ],
            options={
                'unique_together': {('part_template', 'hardware')},
            },
        ),
    ]
