# Generated by Django 5.1.6 on 2026-01-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_calc', '0003_alter_modularproductcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttemplate',
            name='param1_eq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='param2_eq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='shape_type',
            field=models.CharField(default='RECT', max_length=50),
        ),
    ]
