# Generated by Django 5.1.6 on 2025-12-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_calc', '0003_remove_parttemplate_part_thickness_mm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producthardwarerule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='producthardwarerule',
            name='applicability_condition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='producthardwarerule',
            name='quantity_equation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partedgebandwhitelist',
            name='side',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='producthardwarerule',
            name='quantity',
        ),
    ]
