# Generated by Django 5.1.6 on 2025-10-19 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_calc', '0003_parthardwarerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The variable name used in equations (e.g., 'product_length', 'unit_gap').", max_length=50)),
                ('abbreviation', models.CharField(blank=True, help_text="A short abbreviation for display (e.g., 'L', 'W', 'H').", max_length=10)),
                ('default_value', models.DecimalField(blank=True, decimal_places=2, help_text='A default value for the parameter.', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Explains the purpose and constraints of this parameter.')),
                ('product', models.ForeignKey(help_text='The product this parameter belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='modular_calc.modularproduct')),
            ],
            options={
                'ordering': ['product', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
