# Generated by Django 5.1.6 on 2026-02-07 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_calc', '0004_parttemplate_param1_eq_parttemplate_param2_eq_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partedgebandwhitelist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='parttemplate',
            name='edgeband_bottom',
        ),
        migrations.RemoveField(
            model_name='parttemplate',
            name='edgeband_left',
        ),
        migrations.RemoveField(
            model_name='parttemplate',
            name='edgeband_right',
        ),
        migrations.RemoveField(
            model_name='parttemplate',
            name='edgeband_top',
        ),
        migrations.AddField(
            model_name='partedgebandwhitelist',
            name='material_selection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edgeband_options', to='modular_calc.partmaterialwhitelist'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='partedgebandwhitelist',
            name='part_template',
        ),
    ]
