# Generated by Django 5.1.6 on 2025-12-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_calc', '0004_alter_producthardwarerule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='abbreviation',
            field=models.CharField(help_text="A short abbreviation for display (e.g., 'L', 'W', 'H').", max_length=10),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='default_value',
            field=models.DecimalField(decimal_places=2, default=1, help_text='A default value for the parameter.', max_digits=10),
            preserve_default=False,
        ),
    ]
