# Generated by Django 5.1.6 on 2026-02-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_globalvariable_options_alter_tenant_options_and_more'),
        ('material', '0003_alter_woodmaterial_unique_together'),
        ('modular_calc', '0005_alter_partedgebandwhitelist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partedgebandwhitelist',
            unique_together={('material_selection', 'side', 'edgeband', 'tenant')},
        ),
    ]
