# Generated by Django 5.1.6 on 2026-01-01 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard Side Thickness', max_length=100)),
                ('abbr', models.CharField(help_text='e.g., @ST', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('THICKNESS', 'Material Thickness'), ('GAP', 'Construction Gaps'), ('OFFSET', 'Hardware Offsets'), ('METAL', 'Metal Profiles')], default='THICKNESS', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'abbr')},
            },
        ),
    ]
