# Generated by Django 5.1.6 on 2025-12-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EdgebandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in mm (e.g. 2.00)', max_digits=5)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('factor', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_billing_unit_code')],
            },
        ),
        migrations.CreateModel(
            name='CategoryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='material.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='material.categorytypes')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, help_text='Edge band thickness in mm', max_digits=5, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost price per running meter', max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, help_text='Selling price per running meter', max_digits=10)),
                ('wastage_pct', models.DecimalField(decimal_places=2, default=0, help_text='Expected wastage percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.brand')),
                ('edgeband_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='material.edgebandname')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hardware_items', to='material.billingunit')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.brand')),
                ('h_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_items', to='material.hardwaregroup')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('system', models.CharField(choices=[('SI', 'SI'), ('IMPERIAL', 'Imperial'), ('CUSTOM', 'Custom')], max_length=10)),
                ('factor', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='material.measurementunit')),
            ],
        ),
        migrations.CreateModel(
            name='WoodMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(help_text='Surface color / shade (e.g., Walnut, White, Teak)', max_length=50)),
                ('grain', models.CharField(choices=[('NONE', 'No Grain'), ('H', 'Horizontal'), ('V', 'Vertical')], default='NONE', max_length=10)),
                ('length_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('width_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('thickness_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sheet', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.brand')),
                ('cost_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wood_cost_units', to='material.billingunit')),
                ('length_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wood_length_units', to='material.measurementunit')),
                ('material_grp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.category')),
                ('material_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.categorymodel')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.categorytypes')),
                ('sell_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wood_sell_units', to='material.billingunit')),
                ('thickness_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wood_thickness_units', to='material.measurementunit')),
                ('width_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wood_width_units', to='material.measurementunit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categorytypes',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_category_type_name'),
        ),
        migrations.AddConstraint(
            model_name='categorymodel',
            constraint=models.UniqueConstraint(fields=('model_category', 'name'), name='unique_model_name_per_category_type'),
        ),
        migrations.AlterUniqueTogether(
            name='edgeband',
            unique_together={('edgeband_name', 'brand', 'thickness')},
        ),
        migrations.AlterUniqueTogether(
            name='hardware',
            unique_together={('h_group', 'h_name', 'brand')},
        ),
        migrations.AddConstraint(
            model_name='measurementunit',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_measurement_unit_code'),
        ),
        migrations.AlterUniqueTogether(
            name='woodmaterial',
            unique_together={('material_grp', 'material_type', 'material_model', 'name', 'brand')},
        ),
    ]
