# Generated by Django 5.1 on 2025-06-07 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='material.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Models', to='material.categorytypes')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_depth', models.IntegerField(default=0)),
                ('e_thickness', models.FloatField()),
                ('p_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('s_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('set', 'set'), ('each', 'each'), ('nos', 'nos')], default='each', max_length=32)),
                ('p_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('s_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sl_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.brand')),
                ('h_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_items', to='material.hardwaregroup')),
            ],
        ),
        migrations.CreateModel(
            name='WoodEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('grain', models.CharField(choices=[('0', 'Horizontal'), ('1', 'None'), ('2', 'Vertical')], default='2', max_length=3)),
                ('length', models.IntegerField()),
                ('length_unit', models.CharField(choices=[('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('inch', 'Inch'), ('ft', 'Foot')], default='mm', max_length=5)),
                ('width', models.IntegerField()),
                ('width_unit', models.CharField(choices=[('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('inch', 'Inch'), ('ft', 'Foot')], default='mm', max_length=5)),
                ('thickness', models.CharField(max_length=50)),
                ('thickness_unit', models.CharField(choices=[('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('inch', 'Inch'), ('ft', 'Foot')], default='mm', max_length=5)),
                ('p_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('p_price_sft', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costprice_type', models.CharField(choices=[('panel', 'Panel Price'), ('sft', 'Price Per Sqft')], default='panel', max_length=10)),
                ('s_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('s_price_sft', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sellprice_type', models.CharField(choices=[('panel', 'Panel Price'), ('sft', 'Price Per Sqft')], default='panel', max_length=10)),
                ('color', models.CharField(default='no color', max_length=50)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.brand')),
                ('compatible_edgebands', models.ManyToManyField(blank=True, related_name='compatible_woodens', to='material.edgeband')),
                ('material_grp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wooden', to='material.category')),
                ('material_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wooden_models', to='material.categorymodel')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wooden', to='material.categorytypes')),
            ],
        ),
    ]
