# Generated by Django 5.1.6 on 2025-08-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EdgebandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="e.g., 'White 1mm', 'Wood Grain 2mm'", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='material.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Models', to='material.categorytypes')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_depth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('e_thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('s_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.brand')),
                ('edgeband_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.edgebandname')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('set', 'set'), ('each', 'each')], default='each', max_length=32)),
                ('p_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('s_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.brand')),
                ('h_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_items', to='material.hardwaregroup')),
            ],
        ),
        migrations.CreateModel(
            name='WoodEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('grain', models.CharField(choices=[('0', 'Horizontal'), ('1', 'None'), ('2', 'Vertical')], default='2', max_length=3)),
                ('length', models.IntegerField()),
                ('length_unit', models.CharField(choices=[('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('inch', 'Inch'), ('ft', 'Foot')], default='mm', max_length=5)),
                ('width', models.IntegerField()),
                ('width_unit', models.CharField(choices=[('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('inch', 'Inch'), ('ft', 'Foot')], default='mm', max_length=5)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thickness_unit', models.CharField(choices=[('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('inch', 'Inch'), ('ft', 'Foot')], default='mm', max_length=5)),
                ('p_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('p_price_sft', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costprice_type', models.CharField(choices=[('panel', 'Panel Price'), ('sft', 'Price Per Sqft')], default='panel', max_length=10)),
                ('s_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('s_price_sft', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sellprice_type', models.CharField(choices=[('panel', 'Panel Price'), ('sft', 'Price Per Sqft')], default='panel', max_length=10)),
                ('color', models.CharField(default='no color', max_length=50)),
                ('is_sheet', models.BooleanField(default=True, help_text='Is this WoodEn item a standard sheet material for cutting optimization?')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.brand')),
                ('material_grp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wooden', to='material.category')),
                ('material_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wooden_models', to='material.categorymodel')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wooden', to='material.categorytypes')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categorytypes',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_category_type_name'),
        ),
        migrations.AddConstraint(
            model_name='categorymodel',
            constraint=models.UniqueConstraint(fields=('model_category', 'name'), name='unique_model_name_per_category_type'),
        ),
        migrations.AlterUniqueTogether(
            name='edgeband',
            unique_together={('edgeband_name', 'edge_depth', 'e_thickness', 'brand')},
        ),
        migrations.AddConstraint(
            model_name='hardware',
            constraint=models.UniqueConstraint(fields=('h_group', 'h_name', 'brand'), name='unique_hardware_per_group_brand'),
        ),
        migrations.AlterUniqueTogether(
            name='wooden',
            unique_together={('name', 'material_grp', 'material_type', 'material_model', 'brand')},
        ),
    ]
