# Generated by Django 5.1.6 on 2025-12-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingunit',
            name='unique_billing_unit_code',
        ),
        migrations.RemoveConstraint(
            model_name='measurementunit',
            name='unique_measurement_unit_code',
        ),
        migrations.AddConstraint(
            model_name='billingunit',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_billing_unit_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='measurementunit',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_measurement_unit_tenant_code'),
        ),
    ]
