# Generated by Django 5.1.6 on 2025-08-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edgeband',
            unique_together={('edgeband_name', 'e_thickness', 'brand')},
        ),
        migrations.AddField(
            model_name='edgebandname',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Depth in mm, e.g., 2.00', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edgebandname',
            name='name',
            field=models.CharField(default=1, editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='edgeband',
            name='edge_depth',
        ),
    ]
