# Generated by Django 5.1.6 on 2025-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wooden',
            name='thickness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
