# Generated by Django 5.1.6 on 2026-01-13 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_globalvariable_options_alter_tenant_options_and_more'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingunit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='edgeband',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='edgebandname',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='hardwaregroup',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='woodmaterial',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant'),
        ),
    ]
