# Generated by Django 5.1.6 on 2025-06-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_wooden_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wooden',
            name='thickness',
            field=models.CharField(max_length=5),
        ),
    ]
