# Generated by Django 5.1.6 on 2025-12-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('material', '0002_remove_billingunit_unique_billing_unit_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hardware',
            unique_together={('tenant', 'h_group', 'h_name', 'brand')},
        ),
    ]
