# Generated by Django 5.1.6 on 2026-01-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_globalvariable_options_alter_tenant_options_and_more'),
        ('material', '0002_alter_billingunit_tenant_alter_brand_tenant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='woodmaterial',
            unique_together={('tenant', 'material_grp', 'material_type', 'material_model', 'name', 'brand', 'grain')},
        ),
    ]
