# Generated by Django 5.1.6 on 2025-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_wooden_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeband',
            name='name',
            field=models.CharField(blank=True, help_text="e.g., 'White 1mm', 'Wood Grain 2mm'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wooden',
            name='is_sheet',
            field=models.BooleanField(default=True, help_text='Is this WoodEn item a standard sheet material for cutting optimization?'),
        ),
        migrations.AlterField(
            model_name='edgeband',
            name='e_thickness',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='edgeband',
            name='edge_depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='wooden',
            name='thickness',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
