# Generated by Django 5.1.6 on 2026-02-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_woodmaterial_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodmaterial',
            name='cost_price_panel',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='woodmaterial',
            name='cost_price_sft',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='woodmaterial',
            name='length_mm',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='woodmaterial',
            name='sell_price_panel',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='woodmaterial',
            name='sell_price_sft',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='woodmaterial',
            name='thickness_mm',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='woodmaterial',
            name='width_mm',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
