# Generated by Django 5.1.6 on 2025-06-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_edgeband_name_wooden_is_sheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='sl_price',
        ),
        migrations.AlterField(
            model_name='hardware',
            name='unit',
            field=models.CharField(choices=[('set', 'set'), ('each', 'each')], default='each', max_length=32),
        ),
        migrations.AlterField(
            model_name='hardwaregroup',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
