# Generated by Django 5.1 on 2025-06-07 01:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('Standard', 'Standard Product'), ('Modular', 'Modular Product'), ('Custom', 'Custom Product')], default='Standard', help_text='Defines the fundamental type of the product (e.g., Standard, Modular, Custom).', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='A short, unique, human-readable identifier for use in URLs.', max_length=255, null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='Title for search engines (max 60-70 characters).', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Description for search engines (max 150-160 characters).', null=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO.', max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='material.brand')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='model_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='module_images/')),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('threed_model_file', models.FileField(blank=True, help_text='Upload a 3D model file (e.g., .obj, .gltf) for this module blueprint.', null=True, upload_to='module_3d_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productcategory_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('manual_purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manual_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('design_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ModularProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('description', models.TextField(blank=True, help_text='A general description of this modular product blueprint.', null=True)),
                ('length_mm_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('length_mm_max', models.DecimalField(decimal_places=2, default=99999, max_digits=10)),
                ('width_mm_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('width_mm_max', models.DecimalField(decimal_places=2, default=99999, max_digits=10)),
                ('height_mm_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('height_mm_max', models.DecimalField(decimal_places=2, default=99999, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Optional: Manual selling price for the modular product blueprint. If not set, it's derived from module costs + markup.", max_digits=10, null=True)),
                ('threed_model_assembly_file', models.FileField(blank=True, help_text='Upload a base 3D assembly file (e.g., .gltf) for this product.', null=True, upload_to='modular_product_3d_assemblies/')),
                ('threed_config_json', models.JSONField(blank=True, help_text='JSON configuration for 3D viewer (e.g., camera defaults, light settings).', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='StandardProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('section', models.CharField(choices=[('DESKING', 'DESKING'), ('PARTITION', 'PARTITION'), ('COMBO', 'COMBO')], default='DESKING', max_length=30)),
                ('material_description', models.CharField(blank=True, help_text="General description of the material/finish (e.g., 'Melamine White', 'Solid Oak')", max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('s_price', models.DecimalField(decimal_places=2, help_text='Inputted selling price for the standard product.', max_digits=10)),
                ('p_price', models.DecimalField(decimal_places=2, help_text='Inputted purchase price for the standard product (cost to you).', max_digits=10)),
                ('sl_price', models.DecimalField(decimal_places=2, default=0, help_text='Calculated selling price (e.g., P_Price * 1.20).', max_digits=8)),
                ('price_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_products', to='products.model'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('part_length_formula', models.CharField(blank=True, help_text="Formula for length in mm, e.g., 'L - 50'", max_length=255, null=True)),
                ('part_width_formula', models.CharField(blank=True, help_text="Formula for width in mm, e.g., 'W - 50'", max_length=255, null=True)),
                ('part_thickness_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed thickness in mm', max_digits=6, null=True)),
                ('part_quantity_formula', models.CharField(blank=True, default='1', help_text="Formula for quantity, e.g., '1' or '2 * (L / 100)'", max_length=255, null=True)),
                ('wastage_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Factor to account for material wastage (e.g., 1.05 for 5% wastage).', max_digits=5)),
                ('cutting_cost_per_meter', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('grooving_cost_per_meter', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('edgeband_cutting_cost_per_meter', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('shape_type', models.CharField(choices=[('rectangular', 'Rectangular'), ('l_shape', 'L Shape'), ('trapezoid', 'Trapezoid'), ('curved', 'Curved'), ('custom', 'Custom')], default='rectangular', max_length=50)),
                ('geometry_features', models.JSONField(blank=True, help_text="Specific dimensions/parameters for complex shapes (e.g., {'radius': 500, 'angle': 90} for curved)", null=True)),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=20)),
                ('threed_model_file', models.FileField(blank=True, help_text='Upload a 3D model file (e.g., .obj, .gltf) for this part blueprint.', null=True, upload_to='part_3d_models/')),
                ('bottom_edge_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_with_bottom_eb', to='material.edgeband')),
                ('left_edge_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_with_left_eb', to='material.edgeband')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_using_this_wood', to='material.wooden')),
                ('right_edge_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_with_right_eb', to='material.edgeband')),
                ('top_edge_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_with_top_eb', to='material.edgeband')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='type_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='products.productcategory')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_products', to='products.type'),
        ),
        migrations.AddField(
            model_name='model',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.type'),
        ),
        migrations.CreateModel(
            name='ModularProductModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of this module used in the product.')),
                ('position_x', models.DecimalField(decimal_places=2, default=0, help_text='X position (mm) of the module within the product assembly.', max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=2, default=0, help_text='Y position (mm) of the module within the product assembly.', max_digits=10)),
                ('position_z', models.DecimalField(decimal_places=2, default=0, help_text='Z position (mm) of the module within the product assembly.', max_digits=10)),
                ('orientation_roll', models.DecimalField(decimal_places=2, default=0, help_text='Roll rotation (degrees) for 3D visualization.', max_digits=5)),
                ('orientation_pitch', models.DecimalField(decimal_places=2, default=0, help_text='Pitch rotation (degrees) for 3D visualization.', max_digits=5)),
                ('orientation_yaw', models.DecimalField(decimal_places=2, default=0, help_text='Yaw rotation (degrees) for 3D visualization.', max_digits=5)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_product_usages', to='products.module')),
                ('modular_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modular_product_modules', to='products.modularproduct')),
            ],
            options={
                'verbose_name': 'Modular Product Module Component',
                'verbose_name_plural': 'Modular Product Module Components',
            },
        ),
        migrations.AddField(
            model_name='modularproduct',
            name='modules',
            field=models.ManyToManyField(related_name='used_in_products', through='products.ModularProductModule', to='products.module'),
        ),
        migrations.CreateModel(
            name='StandardProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='standard_product_images/')),
                ('standard_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.standardproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ModulePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_parts', to='products.module')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_modules', to='products.part')),
            ],
            options={
                'verbose_name': 'Module Part',
                'verbose_name_plural': 'Module Parts',
                'unique_together': {('module', 'part')},
            },
        ),
        migrations.CreateModel(
            name='PartHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(default=1)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_parts', to='material.hardware')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_hardware', to='products.part')),
            ],
            options={
                'verbose_name': 'Part Hardware Requirement',
                'verbose_name_plural': 'Part Hardware Requirements',
                'unique_together': {('part', 'hardware')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('type', 'name')},
        ),
        migrations.CreateModel(
            name='ModularProductMaterialOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_purchase_price_sft', models.DecimalField(blank=True, decimal_places=4, help_text='Negotiated purchase price per square foot for this material ONLY for this product.', max_digits=10, null=True)),
                ('override_selling_price_sft', models.DecimalField(blank=True, decimal_places=4, help_text='Negotiated selling price per square foot for this material ONLY for this product.', max_digits=10, null=True)),
                ('is_preferred', models.BooleanField(default=True, help_text='Is this material explicitly preferred or allowed for this product?')),
                ('notes', models.TextField(blank=True, help_text='Any specific notes about this material override.', null=True)),
                ('wooden_material', models.ForeignKey(help_text='The specific WoodEn material being overridden or specified.', on_delete=django.db.models.deletion.PROTECT, related_name='product_material_overrides', to='material.wooden')),
                ('modular_product', models.ForeignKey(help_text='The modular product this override applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='material_overrides', to='products.modularproduct')),
            ],
            options={
                'verbose_name': 'Modular Product Material Override',
                'verbose_name_plural': 'Modular Product Material Overrides',
                'unique_together': {('modular_product', 'wooden_material')},
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='products.modularproduct')),
            ],
            options={
                'verbose_name': 'Product Constraint',
                'verbose_name_plural': 'Product Constraints',
                'unique_together': {('product', 'abbreviation')},
            },
        ),
    ]
