# Generated by Django 5.1.6 on 2025-06-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modularproductmaterialoverride',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
