# Generated by Django 5.1.6 on 2025-06-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_modularproductmaterialoverride_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for the setting (e.g., 'sheet_cutting_cost')", max_length=255, unique=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, help_text='Decimal value for the setting (e.g., 115.00)', max_digits=10, null=True)),
                ('string_value', models.CharField(blank=True, help_text="String value for the setting (e.g., 'USD')", max_length=255, null=True)),
                ('boolean_value', models.BooleanField(blank=True, help_text='Boolean value for the setting (e.g., True/False)', null=True)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
