# Generated by Django 5.1.6 on 2025-06-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_globalsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsetting',
            options={},
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='decimal_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='string_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
